# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - supermarketscanner

on:
  push:
    branches:
      - register
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '8'

      - name: Build with Maven
        run: mvn clean install
        working-directory: '${{ github.workspace }}/app'

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/app/target/app-0.0.1-SNAPSHOT.jar'
          
      - name: Distribute jar-war file # Gửi file .jar .war đi đâu, CD nhảy vào ...
        run: mkdir staging && cp '${{ github.workspace }}/app/target/app-0.0.1-SNAPSHOT.jar' staging # tạo thư mục staging chứa file .jar .war sau khi build      
     
      - name: Make hyperlink to jar-war file # Tạo hyperlink để download build 
        uses: actions/upload-artifact@v1
        with:
          name: DOWNLOAD-JAR-WAR-HERE # Bản build được đánh version 1.0-SNAPSHOT
          path: staging

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'supermarketscanner'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_49ED7547AD6B480594C2DCD5C61943D2 }}
          package: 'app-0.0.1-SNAPSHOT.jar'
